

%add the paths to
addpath([getenv('SFINCS_PROJECTSANDTOOLS_HOME'),'/tools/Hakan/BoozerFilesAndGeom']) %This is where readBoozerfile.m resides.
addpath([getenv('SFINCS_PROJECTSANDTOOLS_HOME'),'/tools/Hakan/version3Scans']) 
addpath([getenv('SFINCS_HOME'),'/equilibria/']) 


%bcfile='wout_augh_tony3_short_13surf.bc';
bcfile='wout_augh_tony3_short.bc';
Geom=readBoozerfile(bcfile);

rwishs=0.05:0.05:1;
for ii=1:length(rwishs)
  rinds(ii)=findnearest(Geom.rnorm,rwishs(ii));
end
rnorms=Geom.rnorm(rinds);
ss=Geom.s(rinds);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Profiles %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%n=n0*(1-n1*x^n2)^n3
%dlnndr=n3*(1-n1*s^n2)^(-1)*(-n1*n2*x^(n2-1))/a
n0=0.81*1e20; % m^-3
n1=0.99;
n2=1.2;
n3=0.2;

T0=3.15*1e3; %eV
T1=0.131;
T2=1.730;
T3=15.919;


n=n0*(1-n1*rnorms.^n2).^n3;
T=T0*(1-T1*rnorms.^T2).^T3;
fig(2)
plot(rnorms,n/1e20,rnorms,T/1e3);xlabel('r/a')
fig(3)
plot(ss,n/1e20,ss.^2,T/1e3);xlabel('s=(r/a)^2')

dnds=n0.*n3.*(1-n1*rnorms.^n2).^(n3-1).*(-n1*n2/2*ss.^(n2/2-1));
dTds=T0.*T3.*(1-T1*rnorms.^T2).^(T3-1).*(-T1*T2/2*ss.^(T2/2-1));




outputonscreenonly=1;
 
runspecfile='runspec.dat';
if outputonscreenonly
  runspec_fid=1;
else
  runspec_fid=fopen(runspecfile,'w');
end


%HEADER
fprintf(runspec_fid,'! This file was generated by make_helicalcore_runspecfile.m\n');
fprintf(runspec_fid,'!\n');
fprintf(runspec_fid,['!      rN_wish',...
                    '       nHats_1',...
                    '       nHats_2',...
                    '       THats_1',...
                    '       THats_2',...
                    ' dNHatdpsiNs_1',...
                    ' dNHatdpsiNs_2',...
                    ' dTHatdpsiNs_1',...
                    ' dTHatdpsiNs_2\n']);
          
for rind=1:length(rnorms)
  rnorm=rnorms(rind);

  fprintf(runspec_fid,...
        ['%14.6e%14.6e%14.6e%14.6e%14.6e',...
         '%14.6e%14.6e%14.6e%14.6e\n'],...
        rnorm,n(rind),n(rind),T(rind),T(rind),...
         dnds(rind),dnds(rind),dTds(rind),dTds(rind) );
end

if not(outputonscreenonly)
  fclose(runspec_fid);
end
