function tauE=calctauE(Booz,Vpar,mndPhidpsi)

[kappa,varpi]=Vcomponents(Booz,Vpar)

integrand=...
    (kappa-varpi*(Booz.u-Booz.G./Booz.FSAB2)).*...
    (Booz.u-Booz.G./Booz.FSAB2).*  ...
    2*(Booz.G+Booz.iota.*Booz.I)./Booz.B.^3 .* ...
    (Booz.G.*Booz.dBdtheta-Booz.I.*Booz.dBdzeta);

tauE = -mndPhidpsi*FSA(Booz,integrand);