#!/usr/bin/env python



import os, inspect, math, subprocess, sys, argparse
import numpy as np
from sys import argv
import matplotlib.pyplot as plt

def parse_args(argv):

    parser = argparse.ArgumentParser(description='Launch a DKES calculation')
    parser.add_argument('Sfincsoutfile', type=str)
    return parser.parse_known_args(argv[1:])

#arg, arg_remains = parse_args(sys.argv)
#Sfincsoutfile=arg.Sfincsoutfile
Sfincsoutfile='Sfincs.out'
namelistfile='input.namelist'

try:
  f=open(Sfincsoutfile,'r')
except:
  sys.exit('Could not read '+Sfincsoutfile)


print('reading...')
eof=False
residual=[]
solvertime=[]

while not(eof):
  tmp_str=f.readline()
  while not('ELAPSED TIME IN SOLVE DRIVER' in tmp_str):
  #while not('KSP Residual norm' in tmp_str):
    tmp_str=f.readline()
    if not tmp_str:
      eof=True
      break
  if not(eof):
    solvertime.append(float(tmp_str[tmp_str.find('=')+1:]))

    resnorm_str=f.readline()
    try:
      residual.append(float(resnorm_str[resnorm_str.find('norm')+4:]))
    except:
      print(len(residual))
      print('Could not read norm from string:')
      print(resnorm_str)
      print('Index:')
      print(str(resnorm_str.find('norm')+4))

#print('closing '+Sfincsoutfile)
f.close()

if len(residual)==0:
  sys.exit('No iterations recorded yet.')
if len(residual)==1:
  sys.exit('Only one iteration recorded so far.')

solverTolerance=None
try:
  f=open(namelistfile,'r')
except:
  sys.exit('Could not read '+namelistfile)

#eof=False
while True:#not(eof):
  tmp_str=f.readline()
  if not tmp_str:
    #eof=True
    break
  if tmp_str.find('solverTolerance =')!=-1 or tmp_str.find('solverTolerance=')!=-1:
    rest_str=tmp_str[tmp_str.find('=')+1:]
    if rest_str.find('!')!=-1:
      solverTolerance=float(rest_str[:rest_str.find('!')]) 
    else:
      solverTolerance=float(rest_str)

#print('closing '+namelistfile)
f.close()

print('plotting...')

res=np.array(residual)
Dtime=np.array(solvertime)
time_minutes=np.cumsum(Dtime)/60.0
itervec=np.arange(len(res))

#fig, (ax0,ax1) = plt.subplots(2,1,sharex=True,figsize=(6,7))
fig, (ax0,ax1,ax2) = plt.subplots(3,1,sharex=False,figsize=(6,10))


ax0.semilogy(time_minutes,res/res[0],'o-')
if not(solverTolerance is None):
  ax0.semilogy(time_minutes,solverTolerance*np.ones_like(time_minutes),'--')
  ax0.legend(('residual','tolerance'))
ax0.set_ylabel('relative')
ax0.set_xlabel('time [min]')

ax1.semilogy(res/res[0],'o-')
if not(solverTolerance is None):
  ax1.semilogy(itervec,solverTolerance*np.ones_like(itervec),'--')
  ax1.legend(('residual','tolerance'))
ax1.set_ylabel('relative')
ax1.set_xlabel('iterations')

ax2.semilogy(res,'o-')
ax2.set_ylabel('absolute')
ax2.set_xlabel('iterations')


plt.show()
