#!/usr/bin/env python



import os, inspect, math, subprocess, sys, argparse
from sys import argv

def parse_args(argv):

    parser = argparse.ArgumentParser(description='Launch a DKES calculation')
    parser.add_argument('therange', type=str)
    return parser.parse_known_args(argv[1:])

arg, arg_remains = parse_args(sys.argv)
therange=arg.therange

startjob,stopjob=therange.split('-')

command = 'squeue -u smithh'
result = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
jobs = result.stdout.read().split('\n')


for i in range(len(jobs)):
   if len(jobs[i].split()) < 1:
      continue
   elif (jobs[i].split())[0].isdigit():
      if int((jobs[i].split())[0])>=startjob and int((jobs[i].split())[0])<=stopjob:
          command2 = 'scancel ' + (jobs[i].split())[0]
          result2 = subprocess.Popen(command2, shell=True, stdout=subprocess.PIPE)
          print command2
          #print result2.stdout.read()
   else:
      continue

#exit(0)
