#!/usr/bin/env python



import os, inspect, math, subprocess, sys
from sys import argv

command = 'squeue -u smithh --states=pending,running --start'
result = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
jobs = result.stdout.read().split('\n')

for i in range(len(jobs)):
   if len(jobs[i].split()) < 1:
      print(jobs[i][10:38] + jobs[i][47:])
   elif (jobs[i].split())[0].isdigit():
      command2 = 'scontrol show job ' + (jobs[i].split())[0] + ' | grep WorkDir'
      result2 = subprocess.Popen(command2, shell=True, stdout=subprocess.PIPE)
      dir2 = result2.stdout.read()
      print(jobs[i][10:38] + jobs[i][47:] + '   ' + dir2[dir2.find("version3")+9:-3])
   else:
      print(jobs[i][10:38] + jobs[i][47:])

#exit(0)
