#!/usr/bin/env python



import os, inspect, math, subprocess, sys
from sys import argv

command = 'squeue -u ${USER}'
result = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
jobs = result.stdout.read().split('\n')

for i in range(len(jobs)):
   if len(jobs[i].split()) < 1:
      continue
   elif (jobs[i].split())[0].isdigit():
      command2 = 'scontrol release ' + (jobs[i].split())[0]
      result2 = subprocess.Popen(command2, shell=True, stdout=subprocess.PIPE)
      print result2.stdout.read()
   else:
      continue

#exit(0)
