#!/usr/bin/env ruby

s = `llq -u smithh`

s.each_line do |line|
    # If not a comment:
    if (line[0..1] == "ll")
      if line[2].chr != "q" 
        jobid=line[0..17]
        puts jobid
        puts `llcancel #{jobid}`
      end    
    end
end	    