#!/usr/bin/env python



import os, inspect, math, subprocess
from sys import argv

command = 'llq -l -u smithh | grep "Initial Working Dir"'
result = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
dirs = result.stdout.read().split('\n')

command='llq -u smithh -f %id %dd %st %c'
result = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
info = result.stdout.read().split('\n')



print info[0]
print info[1]
i=0
while i < len(info)-5:
   print info[i+2] + dirs[i][dirs[i].find("version3")+8:]
   i=i+1
